### ISSUE TITLE
freeze/archive and change GitHub metadata 

### ISSUE THREAD

**Issue by paulvi** [InstaDApp/dsa-sdk#109]
If https://github.com/Instadapp/dsa-connect is indeed the latest "The official DSA SDK for JavaScript"

please freeze/archive this repository, and say so in this repository GitHub metadata and give correct link to newer SDK

ref https://github.com/Instadapp/dsa-sdk/issues/108#issuecomment-823200436

**Comment by mubaris** [comment]
I cannot archive the repo, but I have mentioned the link to new SDK
