### ISSUE TITLE
Object-oriented Spell API

### ISSUE THREAD

**Issue by PandaWhisperer** [InstaDApp/dsa-sdk#67]
I find the current Spell API a little bit awkward and I would prefer a more object-oriented interface. As JavaScript is an object-oriented language, I think that would feel more "natural". 

I'm thinking something like this:

```javascript
spell = new dsa.Spell();       // create spell
spell.add({ ... });            // add connectors
await spell.estimateCastGas(); // estimate gas
await spell.cast();            // cast spell
```

What do you think?

It seems that it would be possible to offer this API without breaking backwards compatibility, simply by extracting the ad-hoc spell class from `src/index.js` into a standalone class and binding the existing methods to it. 

I can try working this out and submit a PR if interested.

**Comment by thrilok209** [comment]
Hey @PandaWhisperer , The suggestion you have mentioned makes sense. Can you submit a PR? If everything works as expected, we can give you 100 USDC as grants for this.

**Comment by Sowmayjain** [comment]
Thank you. Its implemented on our new SDK: https://github.com/instadapp/dsa-connect
